### ISSUE TITLE
error: failed to infer module name: unrecognized import path ""

### ISSUE THREAD

**Issue by hitzhangjie** [sourcegraph/lsif-go#197]
Hi, I am a new user to lsif-go, I want to use code intelligence in sourcegraph instead of search-based code navigation.

So I am here and run 'lsif-go' in my git repository, but it reports an error: 

```bash
error: failed to infer module name: unrecognized import path ""
```

I want to know:
- What does the errormsg mean? 
- What should I do to work around this?

**Comment by deepseawhale** [comment]
Got the same issue....

**Comment by tjdevries** [comment]
Hi! Thanks for reporting!

I will be looking into this (but I won't be in office for the next few days, so most of the investigation will come next week).

Could you tell me what the output of this command is in the repository that you're running this in?

```
go list -mod=readonly -m
```

Also, if I created a PR with some additional debugging information, would it be possible to check out the branch, build lsif-go and then run that against your project? That might make debugging it a lot easier.

Thanks!

TJ

**Comment by violetaria** [comment]
I'm seeing this for a [public project/repository](https://gitlab.com/gitlab-org/gitlab-elasticsearch-indexer/-/jobs/2303619007) but not sure what's causing the issue.

**Comment by jessequinn** [comment]
private gitlab pipeline with code_navigation is also doing it:

```
code_navigation:
  stage: test
  image: sourcegraph/lsif-go:v1
  allow_failure: true # recommended
  script:
    - lsif-go
  artifacts:
    reports:
      lsif: dump.lsif
```

error in pipeline

```
error: failed to infer module name: unrecognized import path "xxx.xxx.xxx.xxx/.../.../cis-filter-deployer"
```

**Comment by jessequinn** [comment]
the following appears to work on gitlab 14.10

```
code_navigation:
  stage: test
  image: sourcegraph/lsif-go:v1.2
  allow_failure: true
  script:
    - apt-get update && apt-get -yy install libicu-dev
    - lsif-go -o dump.lsif
  artifacts:
    reports:
      lsif: dump.lsif
```
